name: WhiteNoise
services:
  minio:
    container_name: whitenoise_minio
    image: quay.io/minio/minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=123456789
      - MINIO_VOLUMES=/mnt/data
      - MINIO_OPTS=--console-address :9001
    volumes:
      - ./storage:/mnt/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001"
  postgres:
    container_name: whitenoise_postgres
    image: postgres:17.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: WhiteNoises
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
  pgadmin:
    container_name: whitenoise_pgadmin
    image: dpage/pgadmin4:2025-06-27-2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5500:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    container_name: whitenoise_redis
    image: redis:latest
    restart: unless-stopped
    command: >
      --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis
  redisinsight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    container_name: whitenoise_redisinsight
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PASSWORD: 123
    ports:
      - "5540:5540"
  mongodb:
    container_name: whitenoise_mongodb
    image: mongodb/mongodb-community-server:5.0.2-ubuntu2004
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: 123
  mongo-express:
    container_name: whitenoise_mongo_express
    image: mongo-express:1.0-20-alpine3.19
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: mongodb
      ME_CONFIG_BASICAUTH_PASSWORD: 123
volumes:
  pgadmin:
  postgres:
  redis:
  mongo: